version: "2"
run:
  tests: true
  timeout: 5m
linters:
  enable:
    - misspell
    - revive
    - staticcheck
    - govet
    - errcheck
    - gosec
formatters:
  enable:
    - gofmt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
