package flelsp

import (
	"strings"
)

// prefixToCountry is a curated mapping of common callsign prefixes to countries.
// This is not exhaustive but covers a large majority of common contacts.
var prefixToCountry = map[string]string{
	"F":   "France",
	"G":   "England",
	"M":   "England",
	"2":   "England",
	"GM":  "Scotland",
	"GW":  "Wales",
	"GI":  "Northern Ireland",
	"DL":  "Germany",
	"DK":  "Germany",
	"DF":  "Germany",
	"DG":  "Germany",
	"DH":  "Germany",
	"DJ":  "Germany",
	"EA":  "Spain",
	"EB":  "Spain",
	"EC":  "Spain",
	"I":   "Italy",
	"JA":  "Japan",
	"JH":  "Japan",
	"JK":  "Japan",
	"JM":  "Japan",
	"JR":  "Japan",
	"K":   "USA",
	"W":   "USA",
	"N":   "USA",
	"AA":  "USA",
	"AB":  "USA",
	"AC":  "USA",
	"AD":  "USA",
	"AE":  "USA",
	"AF":  "USA",
	"AG":  "USA",
	"AH":  "USA",
	"AI":  "USA",
	"AJ":  "USA",
	"AK":  "USA",
	"AL":  "USA",
	"VE":  "Canada",
	"VA":  "Canada",
	"VK":  "Australia",
	"ZL":  "New Zealand",
	"PY":  "Brazil",
	"LU":  "Argentina",
	"OH":  "Finland",
	"OE":  "Austria",
	"HB":  "Switzerland",
	"LA":  "Norway",
	"SM":  "Sweden",
	"OZ":  "Denmark",
	"PA":  "Netherlands",
	"PI":  "Netherlands",
	"ON":  "Belgium",
	"9A":  "Croatia",
	"S5":  "Slovenia",
	"HA":  "Hungary",
	"OK":  "Czech Republic",
	"OM":  "Slovakia",
	"SP":  "Poland",
	"UR":  "Ukraine",
	"RA":  "Russia",
	"UA":  "Russia",
	"SV":  "Greece",
	"CT":  "Portugal",
	"CU":  "Azores",
	"LX":  "Luxembourg",
	"EI":  "Ireland",
	"E7":  "Bosnia-Herzegovina",
	"LZ":  "Bulgaria",
	"YO":  "Romania",
	"YU":  "Serbia",
	"Z3":  "North Macedonia",
	"ZA":  "Albania",
	"ZF":  "Cayman Islands",
	"ZS":  "South Africa",
	"SV5": "Dodecanese",
	"SV9": "Crete",
	"4X":  "Israel",
	"4Z":  "Israel",
	"VU":  "India",
	"YB":  "Indonesia",
	"YV":  "Venezuela",
	"ZP":  "Paraguay",
	"CX":  "Uruguay",
	"CE":  "Chile",
	"OA":  "Peru",
	"HK":  "Colombia",
	"HC":  "Ecuador",
	"CP":  "Bolivia",
	"TI":  "Costa Rica",
	"YN":  "Nicaragua",
	"YS":  "El Salvador",
	"TG":  "Guatemala",
	"HR":  "Honduras",
	"XE":  "Mexico",
	"HP":  "Panama",
	"CO":  "Cuba",
	"HI":  "Dominican Republic",
	"V5":  "Namibia",
	"A2":  "Botswana",
	"7P":  "Lesotho",
	"3DA": "Eswatini",
	"ZE":  "Zimbabwe",
	"9J":  "Zambia",
	"5Z":  "Kenya",
	"5H":  "Tanzania",
	"ET":  "Ethiopia",
	"ST":  "Sudan",
	"SU":  "Egypt",
	"5N":  "Nigeria",
	"9G":  "Ghana",
	"TU":  "Ivory Coast",
	"6W":  "Senegal",
	"EL":  "Liberia",
	"CN":  "Morocco",
	"7X":  "Algeria",
	"3V":  "Tunisia",
	"5A":  "Libya",
	"HZ":  "Saudi Arabia",
	"A7":  "Qatar",
	"A6":  "UAE",
	"A4":  "Oman",
	"A9":  "Bahrain",
	"JY":  "Jordan",
	"OD":  "Lebanon",
	"YK":  "Syria",
	"YI":  "Iraq",
	"EP":  "Iran",
	"4L":  "Georgia",
	"4J":  "Azerbaijan",
	"EK":  "Armenia",
	"TA":  "Turkey",
	"EX":  "Kyrgyzstan",
	"EY":  "Tajikistan",
	"UK":  "Uzbekistan",
	"UN":  "Kazakhstan",
	"V8":  "Brunei",
	"HS":  "Thailand",
	"XV":  "Vietnam",
	"XU":  "Cambodia",
	"XZ":  "Myanmar",
	"9M":  "Malaysia",
	"9V":  "Singapore",
	"DU":  "Philippines",
	"HL":  "South Korea",
	"DS":  "South Korea",
	"BV":  "Taiwan",
	"BY":  "China",
	"VR":  "Hong Kong",
	"XX9": "Macao",
	"9K":  "Kuwait",
	"9N":  "Nepal",
	"A5":  "Bhutan",
	"S2":  "Bangladesh",
	"4S":  "Sri Lanka",
	"8Q":  "Maldives",
	"T8":  "Palau",
	"V7":  "Marshall Islands",
	"V6":  "Micronesia",
	"V2":  "Antigua Barbuda",
	"V3":  "Belize",
	"V4":  "St Kitts Nevis",
	"J3":  "Grenada",
	"J6":  "St Lucia",
	"J7":  "Dominica",
	"J8":  "St Vincent",
	"8P":  "Barbados",
	"9Y":  "Trinidad Tobago",
	"P4":  "Aruba",
	"PJ":  "Bonaire/Curacao",
	"FM":  "Martinique",
	"FG":  "Guadeloupe",
	"FY":  "French Guiana",
	"FO":  "French Polynesia",
	"FK":  "New Caledonia",
	"FH":  "Mayotte",
	"FR":  "Reunion",
	"FT":  "TAAF",
	"FW":  "Wallis Futuna",
	"FJ":  "Saint Barthelemy",
	"FS":  "Saint Martin",
	"FP":  "Saint Pierre and Miquelon",
	"TK":  "Corsica",
	"VP8": "Falkland Islands",
	"VP9": "Bermuda",
	"VP2": "Anguilla",
	"VP5": "Turks Caicos",
	"ZD7": "St Helena",
	"ZD8": "Ascension",
	"ZD9": "Tristan da Cunha",
	"KH6": "Hawaii",
	"KL7": "Alaska",
	// More European Entities
	"C3":   "Andorra",
	"EU":   "Belarus",
	"EV":   "Belarus",
	"EW":   "Belarus",
	"ES":   "Estonia",
	"OY":   "Faroe Islands",
	"OH0":  "Aland Islands",
	"TF":   "Iceland",
	"IS0":  "Sardinia",
	"IM0":  "Sardinia",
	"YL":   "Latvia",
	"HB0":  "Liechtenstein",
	"LY":   "Lithuania",
	"ER":   "Moldova",
	"3A":   "Monaco",
	"4O":   "Montenegro",
	"JX":   "Jan Mayen",
	"JW":   "Svalbard",
	"CT3":  "Madeira",
	"R1F":  "Franz Josef Land",
	"UA2":  "Kaliningrad",
	"T7":   "San Marino",
	"1A":   "SMOM",
	"EA6":  "Balearic Islands",
	"EA8":  "Canary Islands",
	"EA9":  "Ceuta & Melilla",
	"HV":   "Vatican City",
	"GD":   "Isle of Man",
	"MD":   "Isle of Man",
	"GU":   "Guernsey",
	"MU":   "Guernsey",
	"GJ":   "Jersey",
	"MJ":   "Jersey",
	"ZB":   "Gibraltar",
	"OJ0":  "Market Reef",
	"SV/A": "Mount Athos",
	"ZC4":  "UK Sov. Base (Cyprus)",
	"5B":   "Cyprus",
}

// LookupCountry returns the country name for a given callsign based on its prefix.
// It uses a longest-prefix match.
func LookupCountry(callsign string) string {
	callsign = strings.ToUpper(callsign)
	if callsign == "" {
		return "Unknown"
	}

	// Try prefixes from longest to shortest
	for length := 3; length >= 1; length-- {
		if len(callsign) >= length {
			prefix := callsign[:length]
			if country, ok := prefixToCountry[prefix]; ok {
				return country
			}
		}
	}

	return "Unknown"
}
